name: codechecks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3